version: "3.9"

services:
  api:
    build: ./api
    # image: custom-name
    container_name: api_c
    ports:
      - "3000:3000"
  web:
    build: ./web
    container_name: web_c
    ports:
      - "5173:5173"
